admin:
  port: 9990
  ip: 0.0.0.0

routers:
- protocol: http
  httpAccessLog: /var/log/linkerd/assets-api/access.log
  label: AssetAPI
  dstPrefix: /assets/http
  dtab:
    /assets/http => /#/apis/assets;
  servers:
  - port: 9001
    ip: 0.0.0.0
- protocol: http
  httpAccessLog: /var/log/linkerd/uploads-api/access.log
  label: UploadAPI
  dstPrefix: /uploads/http
  dtab:
    /uploads/http => /#/apis/uploads;
  servers:
  - port: 9002
    ip: 0.0.0.0
- protocol: http
  httpAccessLog: /var/log/linkerd/metadata-api/access.log
  label: MetadataAPI
  dstPrefix: /metadatas/http
  dtab:
    /metadatas/http => /#/apis/metadatas;
  servers:
  - port: 9003
    ip: 0.0.0.0

namers:
- kind: io.l5d.fs
  prefix: /apis
  rootDir: /disco/apis