admin:
  port: 9991
  ip: 0.0.0.0

storage:
  kind: io.l5d.inMemory
  namespaces:
    assets:
      /svc => /#/apis/assets;
    metadatas:
      /svc => /#/apis/metadatas;
    uploads:
      /svc => /#/apis/uploads;

namers:
- kind: io.l5d.fs
  prefix: /apis
  rootDir: /disco/apis

interfaces:
- kind: io.l5d.thriftNameInterpreter
  port: 4321
  ip: 0.0.0.0